# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SaadTask' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] =
          target.name == 'fmt' ? 'gnu++17' : 'gnu++20'
        build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        build_config.build_settings['WARNING_CFLAGS'] = '$(inherited) -Wno-error'
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -std=gnu++20 -Wno-error'
        if target.name == 'fmt'
          build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] =
            '$(inherited) FMT_USE_CONSTEXPR=0 FMT_USE_CONSTEVAL=0 FMT_USE_NONTYPE_TEMPLATE_ARGS=0'
          build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -std=gnu++17 -Wno-error'
        end
      end
    end
  end
end
